### ISSUE TITLE
Add codecov and travisCI

### ISSUE THREAD

**Issue by mk4111** [SimonLab/tags-system#14]
Remember to add codecov and travisCI - either for this repo or for the more 'refined' version!

**Comment by JMurphyWeb** [comment]
I have done a bit of looking into setting up travis:

specify node version and pg connection & create database in .tavisyml
```
language: node_js
node_js:
  - "4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
```

specify the node version in package.json
```
  "engines" : { "node" : "4" },
```
